// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClFBc-M2COhEaxyCxOPgBGgKDX-K95P84',
    appId: '1:304317268768:web:edbe77eebc16eb31308d45',
    messagingSenderId: '304317268768',
    projectId: 'e-course-af394',
    authDomain: 'e-course-af394.firebaseapp.com',
    storageBucket: 'e-course-af394.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2l31VyTbNgpEbhdSDfPCeX2mcHpmKJ8',
    appId: '1:304317268768:android:261bdb709c1247f9308d45',
    messagingSenderId: '304317268768',
    projectId: 'e-course-af394',
    storageBucket: 'e-course-af394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFeiQBiX7G82sVIJFA7O1cUnC9Gdvnptk',
    appId: '1:304317268768:ios:2051093ccb0f48b5308d45',
    messagingSenderId: '304317268768',
    projectId: 'e-course-af394',
    storageBucket: 'e-course-af394.appspot.com',
    iosBundleId: 'com.example.acourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFeiQBiX7G82sVIJFA7O1cUnC9Gdvnptk',
    appId: '1:304317268768:ios:2051093ccb0f48b5308d45',
    messagingSenderId: '304317268768',
    projectId: 'e-course-af394',
    storageBucket: 'e-course-af394.appspot.com',
    iosBundleId: 'com.example.acourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClFBc-M2COhEaxyCxOPgBGgKDX-K95P84',
    appId: '1:304317268768:web:4404ffe03c674145308d45',
    messagingSenderId: '304317268768',
    projectId: 'e-course-af394',
    authDomain: 'e-course-af394.firebaseapp.com',
    storageBucket: 'e-course-af394.appspot.com',
  );
}
